# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55dcd535ba80761d727b20c7e294df2c9a03d751bea31f6fce0342ed9180843a6d58605b68217af706a11ef3d2fb9f1f3ed80d0129300c8244e87c6b491a74b8

test:
  secret_key_base: ed21f6ac730519262832bfe48c750eb7d8abf7ee15c7d432ce85267b39a3c8632e781c351b2744635d0cde2d6e0d4779f18abdaa949309b93b84cf6e02a3bb45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>